### ISSUE TITLE
Check medium of phone number or status of messages

### ISSUE THREAD

**Issue by knotbin** [jameskabbes/imessage#11]
Is there any way with this library to check the medium (iMessage vs SMS) of a number before sending so we know whether to send an iMessage or a SMS. Otherwise, can we check the status of messages to see if they had errors delivering, and if so send a different type of message?

**Comment by jameskabbes** [comment]
Hi!

1. **Check Medium** - In this library, that functionality does not exist. However, I have seen other people build more complicated applications that 1) input the phone number into the messages app 2) wait 3) check the color (blue or green) and 4) send the message via the appropriate medium.
2. **Status of Delivery** - I never found a way to get a "success/fail" delivery response from the AppleScript. Technically, the AppleScript succeeds in running, even though the message might go undelivered. I'd love to find a way to check this.

If you figure out a solution for either, please submit a pull request!
