### ISSUE TITLE
can't send SMS

### ISSUE THREAD

**Issue by nexttechlife8** [jameskabbes/imessage#2]
Hi There,

it works with iMessage, but not SMS.

message_obj.PhoneNumbers.make_PhoneNumber( '123-555-5555', medium = 'SMS' )

When trying to send as SMS, it has the following errors:

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kabbes_imessage/message_mediums/SMS.applescript:127:130: execution error: The variable SMS is not defined. (-2753)

**Comment by jameskabbes** [comment]
Hi, 

I have tested out the package via the pip install and wasn't able to replicate your error. When sending SMS messages on a Mac, you need to have a nearby iPhone connected that is able to send SMS. Without it, the Mac is only able to send iMessages. If you are still unable to send SMS, send me more information about your environment and I will see what I can find.
