### ISSUE TITLE
Can't tell when message fails to send

### ISSUE THREAD

**Issue by jcsla** [jameskabbes/imessage#7]
First of all, your library is so awesome I think.

I have question though.

If receiver who are not use iMessage, Message sent fails in iMessage app in Mac.

Is any other way to know status of instruction of AppleScript?

Thanks.

**Comment by jcsla** [comment]
I want to send SMS when it fails.

**Comment by jameskabbes** [comment]
Hi there, glad you found some use in the library! I haven't really worked on it in years, but I hope the core functionality works just fine for you.

I tried for a long time, but was never able to find a way to see if a given phone number had iMessage enabled. The only way you can (currently) tell is after the fact when the Messages app tells you that the message send failed. I could never find a way to get the error returned back into Python via the AppleScript. If you find a way to do this, please submit a pull request!

Generally, I will default to an SMS message when I don't know the phone number. However, if I have the number stored in my contacts as an iPhone, I will send them an iMessage.

Hope this helps!
